### ISSUE TITLE
Export python documentation so that editors and help function can display docs

### ISSUE THREAD

**Issue by Neppord** [talonvoice/talon#116]
When I run help on talon api in the repl I would expect to see documentation for the api.

Instead I receive a error message
``` python
>>> help(talon.actions)
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\tokenize.py", line 385, in find_cookie
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdb in position 1: invalid continuation byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\_sitebuiltins.py", line 103, in __call__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1892, in __call__
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1951, in help
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1671, in doc
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1664, in render_doc
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 387, in document
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1243, in docclass
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 95, in getdoc
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\inspect.py", line 839, in getcomments
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\inspect.py", line 782, in findsource
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\linecache.py", line 47, in getlines
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\linecache.py", line 136, in updatecache
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\tokenize.py", line 449, in open
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\tokenize.py", line 426, in detect_encoding
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\tokenize.py", line 390, in find_cookie
  File "<string>", line None
SyntaxError: invalid or missing encoding declaration for 'C:\\Program Files\\Talon\\lib\\site-packages\\talon\\scripting\\actions.py4'
```

**Comment by lunixbochs** [comment]
This error is fixed in the next beta release.
