### ISSUE TITLE
Cannot install pynput using talon's pip

### ISSUE THREAD

**Issue by mqnc** [talonvoice/talon#154]
I am running Ubuntu 18.04.

Running `~/.talon/bin$ ./pip install pynput` causes

```
   ERROR: Command errored out with exit status 1:
     command: /home/me/development/talon/resources/python/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m6h8pq52/evdev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m6h8pq52/evdev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rj5qf9qo
         cwd: /tmp/pip-install-m6h8pq52/evdev/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/me/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/me/.local/lib/python3.7/site-packages/setuptools/dist.py", line 36, in <module>
        from setuptools import windows_support
      File "/home/me/.local/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "lib/python3.7/ctypes/__init__.py", line 7, in <module>
    ImportError: libffi.so.7: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Just for testing I also installed matplotlib which worked fine.

EDIT:

Sorry, matplotlib was already there. However, I could install flask but not dragonmapper.

**Comment by lunixbochs** [comment]
fixed in next beta by setting `LD_LIBRARY_PATH` in `.talon/bin/python`
