### ISSUE TITLE
Dragon and Talon hung (spinners)

### ISSUE THREAD

**Issue by dopey** [talonvoice/talon#19]
Out of the blue started getting a cascade of these errors 

    2018-03-09` 11:24:01 ERROR cb error <class 'talon.ui.Mon'> topic="app_activate" cb=<bound method ContextGroup.ui_event of <talon.voice.ContextGroup object at 0x0000000107929b08>>
    Traceback (most recent call last):
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/dispatch.py", line 58, in safe_call
        return self.call(cb, args)
       File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/dispatch.py", line 54, in call
        return cb(*args)
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/voice.py", line 251, in ui_event
    self.update_scope()
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/voice.py", line 259, in update_scope
        self.reload()
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/voice.py", line 243, in reload
        engine.load(self.grammar)
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/engine.py", line 91, in load
        resp = grammar.load(self)
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/grammar.py", line 88, in load
        resp = self.cmd('g.load', main_rule=f'{self.name}::main', data=self.grammar.data)
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/grammar.py", line 113, in cmd
        return self.engine.cmd(cmd, **kwargs)
      File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/engine.py", line 82, in cmd
        raise EngineCmdErr(f'engine command "{cmd}" failed')
    talon.engine.EngineCmdErr: engine command "g.load" failed`

Both are hung w/ spinners now and neither process will actually die. I've tried quitting both.

**Comment by eliteramen** [comment]
> aegis [11:32 AM]
that's probably #4

https://github.com/talonvoice/talon/issues/4

**Comment by lunixbochs** [comment]
this should be fixed
