### ISSUE TITLE
add a timeout to eye tracker startup

### ISSUE THREAD

**Issue by lexjacobs** [talonvoice/talon#21]
aegis [12:48 PM]
I guess the real solution is for me to add timeouts to eye tracker commands
so it can't freeze outright

```
2018-03-18 12:39:21 DEBUG UI responsive at 0.1144s
2018-03-18 12:39:21 DEBUG [+] /Applications/Talon.app/Contents/Resources/plugins/dragon.py
2018-03-18 12:39:21 DEBUG [+] /Applications/Talon.app/Contents/Resources/plugins/repl.py
2018-03-18 12:39:21 DEBUG [+] /Applications/Talon.app/Contents/Resources/plugins/eye.py
2018-03-18 12:39:26    IO Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Applications/Talon.app/Contents/Resources/pypy/lib-python/3/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Applications/Talon.app/Contents/Resources/pypy/lib-python/3/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/engine.py", line 43, in check_ready
    j = self.cmd('status')
  File "/Applications/Talon.app/Contents/Resources/pypy/site-packages/talon/engine.py", line 82, in cmd
    raise EngineCmdErr(f'engine command "{cmd}" failed')
talon.engine.EngineCmdErr: engine command "status" failed
2018-03-18 12:39:26    IO
```

**Comment by lunixbochs** [comment]
Fixed in 0.0.6.10
