### ISSUE TITLE
v0.1.5 crashes on my Ubuntu Linux desktop

### ISSUE THREAD

**Issue by seawolf** [talonvoice/talon#284]
Hello!

I just upgraded my installation of Talon after being prompted to upgrade to v0.1.5

It's been a while, but if I remember correctly it said to upgrade from v0.1.2 -- whatever it was, the last time I started it, it was fine.

This error shows on start-up:
```
"Failed to set up Python environment:" Traceback (most recent call last):
  File "<init code for 'talon_api'>", line 36, in exec_spec
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "app/resources/init.py", line 17, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "lib/python3.9/logging/config.py", line 30, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "lib/python3.9/logging/handlers.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "lib/python3.9/socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
```

I'm running:

```
>> cat /etc/issue
Ubuntu 18.04.5 LTS

>> python --version
Python 2.7.17
```

I'm unfamiliar with Python so wonder if there's anything I can do to help diagnose?

Many thanks!

**Comment by lunixbochs** [comment]
Seems like file corruption. Try downloading a fresh version of the app from https://talonvoice.com

**Comment by seawolf** [comment]
Yup, fresh install launches okay! The inline updater must have messed something up. Weird.

Thanks for your help!
