### ISSUE TITLE
`talon.mac.ui.App`'s `quit()` raises an exception instead of working

### ISSUE THREAD

**Issue by phillco** [talonvoice/talon#483]
```
>>> ui.apps(name="Code")[0].quit()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "talon/mac/ui.py", line 179, in quit
TypeError: '_Bool(*)(struct ui_mon *, ui_app *)' expects 2 arguments, got 1
```

Sending the app `cmd-q` directly or  raising signals works as a decent workaround in the interim.

**Comment by lunixbochs** [comment]
fixed in next beta
